import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Sidebar } from "../admin/events/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid lg:grid-cols-5">
          <div className="hidden lg:block">
            <Sidebar />
          </div>
          <section className="container py-8 px-8 col-span-3 lg:col-span-4 lg:border-l">
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}
